<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Zapqio.Runner-65c184bc-31b9-405e-ba89-08ed5e04a1b3</UserSecretsId>
    <PlatformTarget Condition="'$(TargetFramework)' == 'net8.0-windows'">x64</PlatformTarget>
	<DeterministicSourcePaths>true</DeterministicSourcePaths>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-windows'">
    <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.2" />
    <PackageReference Include="NJsonSchema" Version="11.5.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.TextWriter" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zapqio.Runner.Module.Core\Zapqio.Runner.Module.Core.csproj" />
    <ProjectReference Include="..\Zapqio.Protocol\Zapqio.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>
</Project>
